# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MergeConflictWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 717)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.conflicts_selection_splitter = QtWidgets.QSplitter(self.centralwidget)
        self.conflicts_selection_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.conflicts_selection_splitter.setObjectName("conflicts_selection_splitter")
        self.layoutWidget = QtWidgets.QWidget(self.conflicts_selection_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.conflicts_list_vertical_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.conflicts_list_vertical_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.conflicts_list_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.conflicts_list_vertical_layout.setSpacing(7)
        self.conflicts_list_vertical_layout.setObjectName("conflicts_list_vertical_layout")
        self.conflicts_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conflicts_label.sizePolicy().hasHeightForWidth())
        self.conflicts_label.setSizePolicy(sizePolicy)
        self.conflicts_label.setObjectName("conflicts_label")
        self.conflicts_list_vertical_layout.addWidget(self.conflicts_label)
        self.conflicts_list_wiget = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conflicts_list_wiget.sizePolicy().hasHeightForWidth())
        self.conflicts_list_wiget.setSizePolicy(sizePolicy)
        self.conflicts_list_wiget.setObjectName("conflicts_list_wiget")
        self.conflicts_list_vertical_layout.addWidget(self.conflicts_list_wiget)
        self.finish_merge_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finish_merge_button.sizePolicy().hasHeightForWidth())
        self.finish_merge_button.setSizePolicy(sizePolicy)
        self.finish_merge_button.setObjectName("finish_merge_button")
        self.conflicts_list_vertical_layout.addWidget(self.finish_merge_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.conflicts_selection_splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.merge_selection_vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.merge_selection_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.merge_selection_vertical_layout.setObjectName("merge_selection_vertical_layout")
        self.file_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_name_label.sizePolicy().hasHeightForWidth())
        self.file_name_label.setSizePolicy(sizePolicy)
        self.file_name_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.file_name_label.setObjectName("file_name_label")
        self.merge_selection_vertical_layout.addWidget(self.file_name_label)
        self.compare_files_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compare_files_button.sizePolicy().hasHeightForWidth())
        self.compare_files_button.setSizePolicy(sizePolicy)
        self.compare_files_button.setMaximumSize(QtCore.QSize(16777215, 60))
        self.compare_files_button.setObjectName("compare_files_button")
        self.merge_selection_vertical_layout.addWidget(self.compare_files_button)
        self.cloud_local_splitter = QtWidgets.QSplitter(self.verticalLayoutWidget)
        self.cloud_local_splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cloud_local_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.cloud_local_splitter.setObjectName("cloud_local_splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.cloud_local_splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.cloud_layout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.cloud_layout.setContentsMargins(0, 0, 0, 0)
        self.cloud_layout.setObjectName("cloud_layout")
        self.cloud_image = QtWidgets.QLabel(self.layoutWidget1)
        self.cloud_image.setMaximumSize(QtCore.QSize(125, 100))
        self.cloud_image.setText("")
        self.cloud_image.setPixmap(QtGui.QPixmap(":/images/ClydePNG.png"))
        self.cloud_image.setScaledContents(True)
        self.cloud_image.setAlignment(QtCore.Qt.AlignCenter)
        self.cloud_image.setObjectName("cloud_image")
        self.cloud_layout.addWidget(self.cloud_image)
        self.take_cloud_changes_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.take_cloud_changes_button.setObjectName("take_cloud_changes_button")
        self.cloud_layout.addWidget(self.take_cloud_changes_button)
        self.layoutWidget2 = QtWidgets.QWidget(self.cloud_local_splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.local_layout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.local_layout.setContentsMargins(0, 0, 0, 0)
        self.local_layout.setObjectName("local_layout")
        self.local_image = QtWidgets.QLabel(self.layoutWidget2)
        self.local_image.setMaximumSize(QtCore.QSize(125, 100))
        self.local_image.setText("")
        self.local_image.setPixmap(QtGui.QPixmap(":/images/KevinPNG.png"))
        self.local_image.setScaledContents(True)
        self.local_image.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.local_image.setObjectName("local_image")
        self.local_layout.addWidget(self.local_image)
        self.take_local_changes_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.take_local_changes_button.setObjectName("take_local_changes_button")
        self.local_layout.addWidget(self.take_local_changes_button)
        self.merge_selection_vertical_layout.addWidget(self.cloud_local_splitter)
        self.verticalLayout_6.addWidget(self.conflicts_selection_splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.conflicts_label.setText(_translate("MainWindow", "List of Conflicts"))
        self.finish_merge_button.setText(_translate("MainWindow", "Done"))
        self.file_name_label.setText(_translate("MainWindow", "{File Name}"))
        self.compare_files_button.setText(_translate("MainWindow", "Compare"))
        self.take_cloud_changes_button.setText(_translate("MainWindow", "Cloud"))
        self.take_local_changes_button.setText(_translate("MainWindow", "Local"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
import gui_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
